# Generated by Django 2.2.3 on 2019-07-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_termin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='termin',
            name='price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
